-- LBE Team Calculator database schema
-- Run this entire file in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.formats (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  updated_by uuid not null references public.profiles(id),
  name text not null check (char_length(name) between 1 and 160),
  description text not null default '',
  visibility text not null default 'team' check (visibility in ('team', 'private')),
  currency text not null default 'USD' check (currency in ('USD', 'CAD', 'EUR', 'GBP', 'AUD')),
  format_data jsonb not null,
  version_number integer not null default 1 check (version_number >= 1),
  last_change_note text not null default 'Created format',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists formats_owner_id_idx on public.formats(owner_id);
create index if not exists formats_updated_at_idx on public.formats(updated_at desc);
create index if not exists formats_visibility_idx on public.formats(visibility);

create table if not exists public.format_versions (
  id bigint generated by default as identity primary key,
  format_id uuid not null references public.formats(id) on delete cascade,
  version_number integer not null,
  name text not null,
  description text not null default '',
  visibility text not null,
  currency text not null,
  format_data jsonb not null,
  change_note text not null default '',
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(format_id, version_number)
);

create index if not exists format_versions_format_id_idx
  on public.format_versions(format_id, version_number desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

create or replace function public.capture_format_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.format_versions (
    format_id,
    version_number,
    name,
    description,
    visibility,
    currency,
    format_data,
    change_note,
    created_by,
    created_at
  ) values (
    new.id,
    new.version_number,
    new.name,
    new.description,
    new.visibility,
    new.currency,
    new.format_data,
    new.last_change_note,
    new.updated_by,
    new.updated_at
  )
  on conflict (format_id, version_number) do nothing;
  return new;
end;
$$;

create or replace function public.update_lbe_format(
  p_format_id uuid,
  p_expected_version integer,
  p_name text,
  p_description text,
  p_visibility text,
  p_currency text,
  p_format_data jsonb,
  p_change_note text
)
returns public.formats
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current public.formats%rowtype;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select *
  into v_current
  from public.formats
  where id = p_format_id
  for update;

  if not found then
    raise exception 'FORMAT_NOT_FOUND';
  end if;

  if v_current.owner_id <> auth.uid() then
    raise exception 'NOT_OWNER';
  end if;

  if v_current.version_number <> p_expected_version then
    raise exception 'VERSION_CONFLICT|current=%', v_current.version_number;
  end if;

  if p_visibility not in ('team', 'private') then
    raise exception 'INVALID_VISIBILITY';
  end if;

  if p_currency not in ('USD', 'CAD', 'EUR', 'GBP', 'AUD') then
    raise exception 'INVALID_CURRENCY';
  end if;

  update public.formats
  set
    name = left(coalesce(nullif(trim(p_name), ''), 'Untitled format'), 160),
    description = coalesce(p_description, ''),
    visibility = p_visibility,
    currency = p_currency,
    format_data = p_format_data,
    version_number = version_number + 1,
    last_change_note = left(coalesce(nullif(trim(p_change_note), ''), 'Updated assumptions'), 240),
    updated_by = auth.uid()
  where id = p_format_id
  returning * into v_current;

  return v_current;
end;
$$;

-- Recreate triggers so rerunning this script is safe.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists formats_set_updated_at on public.formats;
create trigger formats_set_updated_at
  before update on public.formats
  for each row execute function public.set_updated_at();

drop trigger if exists formats_capture_version on public.formats;
create trigger formats_capture_version
  after insert or update of version_number on public.formats
  for each row execute function public.capture_format_version();

-- Backfill profiles for users that existed before this schema was run.
insert into public.profiles (id, email, display_name)
select
  id,
  coalesce(email, ''),
  coalesce(raw_user_meta_data ->> 'display_name', split_part(coalesce(email, ''), '@', 1))
from auth.users
on conflict (id) do update set email = excluded.email;

alter table public.profiles enable row level security;
alter table public.formats enable row level security;
alter table public.format_versions enable row level security;

-- Remove existing policies when rerunning the setup script.
drop policy if exists "Authenticated users can view profiles" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can view visible formats" on public.formats;
drop policy if exists "Users can create their own formats" on public.formats;
drop policy if exists "Owners can delete their formats" on public.formats;
drop policy if exists "Users can view versions of visible formats" on public.format_versions;

create policy "Authenticated users can view profiles"
on public.profiles
for select
to authenticated
using ((select auth.uid()) is not null);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Users can view visible formats"
on public.formats
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or visibility = 'team'
);

create policy "Users can create their own formats"
on public.formats
for insert
to authenticated
with check (
  (select auth.uid()) = owner_id
  and (select auth.uid()) = updated_by
);

create policy "Owners can delete their formats"
on public.formats
for delete
to authenticated
using ((select auth.uid()) = owner_id);

create policy "Users can view versions of visible formats"
on public.format_versions
for select
to authenticated
using (
  exists (
    select 1
    from public.formats f
    where f.id = format_versions.format_id
      and (f.owner_id = (select auth.uid()) or f.visibility = 'team')
  )
);

-- Explicit API grants. Direct UPDATE is intentionally withheld; updates must
-- go through update_lbe_format() so the expected version is checked atomically.
revoke all on public.profiles from anon;
revoke all on public.formats from anon;
revoke all on public.format_versions from anon;

revoke all on public.profiles from authenticated;
revoke all on public.formats from authenticated;
revoke all on public.format_versions from authenticated;

grant select, update on public.profiles to authenticated;
grant select, insert, delete on public.formats to authenticated;
grant select on public.format_versions to authenticated;
grant usage, select on sequence public.format_versions_id_seq to authenticated;

revoke all on function public.update_lbe_format(uuid, integer, text, text, text, text, jsonb, text) from public;
grant execute on function public.update_lbe_format(uuid, integer, text, text, text, text, jsonb, text) to authenticated;

-- Enable low-volume Postgres Changes for automatic library refresh.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'formats'
     ) then
    execute 'alter publication supabase_realtime add table public.formats';
  end if;
end;
$$;
